on: push
name: SonarQube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      run: sonar-scanner
           -Dsonar.projectKey=GitHub-tarikdogdu 
           -Dsonar.sources=. 
           -Dsonar.host.url=http://127.0.0.1:9000
           -Dsonar.login=sqp_681a708c065d63a26c850c766facd72c4de54362
